### ISSUE TITLE
No exception/feedback when sending a text message from an invalid account.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#1]
1. There appears to be a problem on the website, I have a test account with no phone number defined. When I edit my contact details, enter my phone number and click Save, I see the message stating that my account details have been updated but my phone number does not display in the field.  Also, I do not get a text/notification about this change via phone/email.
2. While the above is an issue with the website, it does appear to impact the API as well.  When I attempt to send a text message using that account (with no phone number), my request appears to succeed i.e. there is no error.  I do not think that this is an issue with the Ruby API as I can see the underlying http response, the response code is 201, the payload looks like this:
   `{"id":70781452,"href":"\/api\/v2\/messages\/70781452","type":"message","sessionId":49041039,"bulkId":null,"messageId":70781452,"scheduleId":null}"`

**Comment by matthewcummings** [comment]
OK, I understand how it works now.  When I send texts with my incomplete account, I see the initial message status as 'q'.  I still think the whole operation should just fail if I don't have a valid phone number on my account.  I would go with an HTTP 400 based on this SO discussion: http://stackoverflow.com/questions/6123425/rest-response-code-for-invalid-data

**Comment by andreylarionov** [comment]
You do not need to specify the account phone to send message. If you have a response that contains an `id` that means sending was successful.
