### ISSUE TITLE
Add a new SentMessage class to the API model.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#10]
It's a bit confusing in the Ruby API that when you create (and send) a new message, it contains a very different set of properties than a sent message that you fetch via messages.list().  
This is an example:

```
Textmagic::REST::Client.messages.create()
[:id, 70826055]
[:href, "/api/v2/messages/70826055"]
[:type, "message"]
[:session_id, 49073000]
[:bulk_id, nil]
[:message_id, 70826055]
[:schedule_id, nil]
```

vs.

```
Textmagic::REST::Client.messages.list()
[:id, 70826055]
[:receiver, "15124922388"]
[:message_time, "2015-09-21T05:14:48+0000"]
[:status, "q"]
[:text, "التقليدية قبلוְאָהַבְתָּ אֵתちゅひゃфачтидёеայբուբեն"]
[:charset, "UTF-16BE"]
[:first_name, nil]
[:last_name, nil]
[:country, "US"]
[:sender, "447624800500"]
[:price, 0.012]
[:parts_count, 1]
```

The problem isn't that the two objects have different properties, it's that they are both instances of the same class.  By the way, since this is a reflection of the data model in the core API, this is going to be confusing in the other language wrappers too, not just the Ruby API.   

I have three proposals for how to deal with this:
1) Do nothing and live with it.  

2) Fix it in the Ruby API e.g. create a Message subclass with a name like SentMessage and wrap that around message objects returned from list().

3) Fix it in the underlying REST API. . . this could involve a new sentmessage endpoint.  There doesn't seem to be a quick or clean way to do this.

**Comment by andreylarionov** [comment]
This issue has been discussed many times and was accepted the current solution. This structure is more flexible in our opinion. Perhaps this view will be revised in the future.

**Comment by matthewcummings** [comment]
OK, I find it confusing but I can live with it. :)
