### ISSUE TITLE
No error + templateId ignored when sending SMS message with both params specified.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#11]
This is a minor issue and not specific to the Ruby wrapper, it's in the core REST API.
Submit a message with both the text and templateId fields specified.  I would expect an error in this case but what happens is that the templateId value is ignored.

**Comment by andreylarionov** [comment]
`text` parameter has a higher priority than `template_id` parameter when sending message. I think it will be documented soon.
