### ISSUE TITLE
Enhancement: show templateId value on template settings page.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#12]
It would be convenient for API developers if you provided a way in the online https://my.textmagic.com/online/messages/templates/settings for a user to see the templateId value for a template.  Since the API uses the templateId field, displaying that property from the UI would be helpful.

**Comment by andreylarionov** [comment]
Yes, it will be implemented in web app. Right now you can use `client.templates.list()` to get ID of template.
