### ISSUE TITLE
SMS replies containing non-text content are dropped.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#13]
Not specific to the Ruby wrapper, this occurs in the underlying API.
1. Send an SMS message via TextMagic to a device that you control.
2. When you receive the text respond with text and an image file (any binary file).
3. Wait a bit, then query the replies endpoint.

The reply never makes it to your TextMagic account. . .

**Comment by matthewcummings** [comment]
I would expect to at least receive a text with an error message in this case.

**Comment by andreylarionov** [comment]
TextMagic inbound phone numbers does not support receiving replies containing non-text content.
