### ISSUE TITLE
Document and/or expose time interval for fetching replies

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#17]
I've noticed that when I fetch replies via /api/v2/replies, I only appear to get the replies from the last 24 hours.

This should be documented.  Ideally, the API would support another parameter to allow the user to specify the interval of time to use when fetching replies.  Perhaps something like 1s, 5m, 6h, 8d etc. to specify 1 second back in time, 5 minutes back in time. . .

**Comment by andreylarionov** [comment]
Duplicates #18

**Comment by matthewcummings** [comment]
Sorry about that, not sure how that happened.
