### ISSUE TITLE
Missing reply parameter documentation

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#19]
See the comment here: https://github.com/textmagic/textmagic-rest-ruby/blob/master/lib/textmagic-ruby/rest/replies.rb#L18-L37

There is no mention of the search, query or ids parameters on the website doc page:
https://www.textmagic.com/docs/api/receive-sms/#rest-inbound-messages-management

These parameters should be documented in both places or not at all.

**Comment by andreylarionov** [comment]
Will be documented soon. Thanks.
