### ISSUE TITLE
Change client.messages.create to client.create_message() and message.send()?

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#2]
The current Ruby interface feels a bit awkward, to create AND send a message, you do this:

```
client = Textmagic::REST::Client.new username, token
params = {:phones => '999999999, :text => 'Hello from TextMagic Ruby.'}
message = client.messages.create(params)
```

It would feel a bit more object oriented to make it work something like this:

```
client = Textmagic::REST::Client.new username, token
params = {:phones => '999999999, :text => 'Hello from TextMagic Ruby.'}
message = client.create_message(params)
message.send()
```

I'm not  yet sure how well that will fit with the underlying REST model, but when I see the client.messages.create() method, two issues come to mind:
1. Why isn't create() available on the client object itself?
2. I don't expect the create() method to actually send the message.

Open to suggestions/comments on this.

**Comment by andreylarionov** [comment]
I think the existing architecture is more convenient to understand and flexible to change (add/edit/delete methods). We have a client, client has entities ('messages', 'contacts' etc), each entity has methods (in most cases are identical in nature - 'create', 'list', 'get'). Regarding create of message, if you specify sendingTime parameter in future then your message will be sent later, but if you don't specify sendingTime parameter then message will be sent immediately. In both cases messages will be created (that reflects the name of the method). Perhaps it makes sense to add aliases for the most commonly used methods (like client.create_message()) on the client object. But I'm not sure that we need to change the library's architecture.

**Comment by matthewcummings** [comment]
OK, that makes more sense taking sendingTime into account.  I still think my proposal is better but that would be a huge change to the API.  
:)

I will close this issue.
