### ISSUE TITLE
Bad error message when testing callback URLs with no URL specified.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#21]
1. Go to the API settings page: https://my.textmagic.com/online/api/settings
2. Leaving either Callback URL field blank, click on the Test button.

You receive an error dialog with this message:
**No callback URL specified
We were unable to connect to this callback URL. Please try again.**

Instead you should get something like:
**No callback URL specified
Please enter a valid callback URL and try again.**

**Comment by andreylarionov** [comment]
Fixed and will be soon in production.
