### ISSUE TITLE
Rate limiting appears to be disabled or broken

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#27]
Unless you've radically changed your request frequency limit, it appears to be broken or disabled.  
I can very easily send multiple messages in a loop like this with the Ruby client:

```
 10.times do
   client.messages.create(params)
 end
```

The texts are all sent successfully with no errors at all.

**Comment by andreylarionov** [comment]
Rate limit was changed. It will soon appear in the documentation.

**Comment by matthewcummings** [comment]
OK, thanks.   Good to know.
