### ISSUE TITLE
Minor change to the doc on request frequency limits

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#28]
https://www.textmagic.com/docs/api/restrictions/#api-request-frequency-limit

The wording here is slightly awkward, I'd change the text to read like this:

You may not execute more than 2 requests per second. If you do, a 429 Too Many Requests error will be returned. Please note that you can use contacts, lists and templates for sending multiple messages simultaneously per request.

**Comment by dmitry-textmagic** [comment]
Text changed.
