### ISSUE TITLE
Request: review my latest changes to examples/chats.rb. . .

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#32]
And the other two example scripts I created: send_message.rb and receive_message.rb.  I'd like to update all of the examples to use a similar format.  I find it more readable and educational - the existing examples look and feel like unit tests.  I've been adding comments with links back to the corresponding doc pages (on your site) where possible too.

Let me know your thoughts on that Andrey.
Since github doesn't allow messaging, I created this issue to send this message.  
Thanks,
Matt

**Comment by matthewcummings** [comment]
Note that I added the auth_helper. rb script to encourage users not to copy/paste their credentials directly into the scripts.  Two benefits here:
- They won't accidentally commit their credentials to a shared repot.
- They won't need to copy/paste their credentials into every file and can easily switch accounts by updating the corresponding environment variables.

**Comment by matthewcummings** [comment]
I probably should move auth_helper in ./lib and wrap it in the Textmagic module hierarchy.

**Comment by matthewcummings** [comment]
To elaborate a bit more, when you run an example like contacts.rb, the output doesn't give any clue as to what it refers to.  E.g.

```
 *** Running contact examples *** 
true
true
. . .
true
true
 *** Finish contact examples *** 
```

**Comment by andreylarionov** [comment]
Hi, Matthew
Actually, the existing examples look like unit tests (initially they were designed for this purpose). It is a very good idea to make it a more readable using similar format like you did in chats.rb. 
Thanks.

**Comment by matthewcummings** [comment]
OK, great Andrey.  I will continue updating the existing examples.  I may add some new ones too.
