### ISSUE TITLE
Include the phone number in the field error when creating a contact with an existing number.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#33]
When you attempt to create a new contact with the same phone number as an existing contact, you receive this error:
fields: {"phone"=>["Phone number already exists in your contacts."]}

It would be more helpful if the error included the phone number e.g.
fields: {"phone"=>["An account with the phone number 999123456 already exists in your contacts."]}

**Comment by andreylarionov** [comment]
Good point. Most likely it will be implemented later.
