### ISSUE TITLE
Include the custom field name in the error message when attempting a create with a duplicate name

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#34]
This is analogous to https://github.com/textmagic/textmagic-rest-ruby/issues/33 but for custom fields.  When you try to create a custom field with the same name as an existing custom field, you get this error message:
fields: {"name"=>["This field already exists. Please use a different field name."]}

It would be nice if the actual field name were included e.g.
fields: {"name"=>["This field FIELD_NAME already exists. Please use a different field name."]}

**Comment by andreylarionov** [comment]
See #33
