### ISSUE TITLE
No online documentation for the unsubscribers resource.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#36]
There's an example file for the unsubscriber resource in the Ruby API's examples directory but no mention of this resource anywhere on the API doc pages.  Either the example should be removed or the API documentation should be added.

**Comment by andreylarionov** [comment]
Fixed and will be in production soon. Thanks.

**Comment by matthewcummings** [comment]
You're welcome.  :)
