### ISSUE TITLE
More bad links on the API doc site.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#40]
https://www.textmagic.com/docs/api/
- TextMagic SMS API (at the top of the page) - this links to a password protected test page.
- The node.js and CSharp links don't go anywhere, presumably because those APIs are still a work in progress.

**Comment by matthewcummings** [comment]
https://www.textmagic.com/docs/api/sandbox/

The TextMagic Sandbox at the bottom of the page 404s.

**Comment by matthewcummings** [comment]
https://www.textmagic.com/docs/api/distribution-lists/

The marketing site link points to a password protected page in your test/stage environment

**Comment by matthewcummings** [comment]
https://www.textmagic.com/docs/api/contacts/

Comma-separated list ID - this link 404s.

**Comment by matthewcummings** [comment]
https://www.textmagic.com/docs/api/sub-accounts/

Array of user resources See Account section for details.  The Account link here 404s.

**Comment by matthewcummings** [comment]
https://www.textmagic.com/docs/api/invoices/

You can now check our Code libraries - another 404.

**Comment by matthewcummings** [comment]
https://www.textmagic.com/docs/api/response-codes/
- Current user has no rights to perform the specified action. For example, regular users cannot view Invoices 404 or Sub-Accounts 404 - these two links 404.
- The Restrictions link at the bottom of the page points to the password protected test site.

**Comment by matthewcummings** [comment]
https://www.textmagic.com/docs/api/restrictions/

The Encoding link at the bottom of the page points to the test site too.

**Comment by matthewcummings** [comment]
https://www.textmagic.com/docs/api/perl/

The Download link 404s.

**Comment by dmitry-textmagic** [comment]
Fixed.
