### ISSUE TITLE
Typos on the Send Text Messages doc page

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#42]
https://www.textmagic.com/docs/api/send-sms/
- In the Parameters table, the partsCount section has a typo - "MMaximum".
- Same table, in the "from" section, "f specified" should be "If specified"
- In the Response section, "IIf your request" should be "If your request"
- In the "How to send a single text message" section, "you should set out only" should be "you should set only" 
- In the "How to send bulk text messages" section, this isn't a typo but I would change the wording "You can also send several messages at once." to "You can also send a message to many recipients simultaneously."

**Comment by dmitry-textmagic** [comment]
Fixed, thank you.
