### ISSUE TITLE
Typos on the Sandbox page.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#46]
- In the first paragraph, this text "without the need to yet install any" should be "without the need to install any"
- This sentence sounds a bit awkard "Here, we explain the following aspects:".  I would go with something like "Here, we explain the following details about Sandbox:"
- Minor but I would change this text "documentation about a command, i.e." to "documentation for a command i.e."
- In the How it works section, change this text "To use Sandbox, simply click the Sandbox tab at the command you want to test:" to "To use Sandbox, simply click on the entry for the command you want to test:" [I don't see a tab here]
- Change 
  "The URL you use indicates the command you wish to use, e.g. /api/v2/templates." 
  to 
  "The URL corresponds to the command you wish to use, e.g. /api/v2/templates corresponds to the templates command."
- Change 
  "You will receive a JSON answer showing whether the request was successful or not. It will also return several headers in the Response Body and the Response Header field, respectively, providing additional information." 
  to 
  "You will receive an HTTP response code along with a JSON response body showing whether the request was successful or not.  You will find additional information provided in the HTTP response headers."
- Change
  "From the example above, note the request did not pass the tests for the name and content parameters, as the user had omitted to enter these, and as these are mandatory, the test was not successful. TextMagic API thus returned an error code, with a brief error message and an array showing each field that contained errors." 
  to 
  "In the example above, note that the request failed because the user did not specify values for the name and content fields which are both required. Thus, the TextMagic API thus returned an HTTP error status code, with a brief error message showing which fields contained errors."
- Change 
  "Now, let’s modify the request so that the request will pass all the required parameters. Voilà:" 
  to 
  "Now, let’s modify the request so that it includes both of the required parameters. Voilà:"
- Change
  "Just as we intended, we have now successfully created a new message template, and have saved it to the TextMagic database with the ID number 51386. Now we can send a message using the API or TextMagic Online template."
  to
  "We have now successfully created a new message template, and saved it to the TextMagic database.  It was created with an ID value of 51386. Now we can send a message using this template via API or TextMagic Online." 
- Change 
  "to make requests before writing the code"
  to
  "to make requests without writing code "
- Change 
  "f you need help"
  to 
  "If you need help"

**Comment by dmitry-textmagic** [comment]
Fixed. 

NOTE: changes will be applied during next site rebuild process.
