### ISSUE TITLE
Should receive an http 409 when posting a duplicate contact.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#5]
This is a bug in the underlying REST API, not the Ruby wrapper.  Also, I suspect that it may occur with other entities, not just contacts.  If that turns out to be the case, I will update this issue or create a new one(s).

When you create a new contact using the phone number of an existing contact, the response is an HTTP 400 with this payload

```
"{"code":400,"message":"Validation Failed","errors":{"fields":{"phone":["Phone number already exists in your contacts."]}}}"
```

Instead, the response code should be a 409.  Also, it would be nice if the phone number were included in the payload.  It would make it easier for the user to track down the issue.

Not a serious issue, nonetheless see this SO post for more details about the expected REST results for a case like this: http://stackoverflow.com/questions/3290182/rest-http-status-codes-for-failed-validation-or-invalid-duplicate

**Comment by matthewcummings** [comment]
NOTE: the behavior of REST calls in cases like this is often debatable.  I believe that the above change would be better and more compliant with REST "standards" but this is not a serious issue.
This change will entail documentation changes as well.

**Comment by andreylarionov** [comment]
According to Wikipedia:

> 409 Conflict
> Indicates that the request could not be processed because of conflict in the request, such as an edit conflict in the case of multiple updates.

I suppose we have an error of another kind is not associated with the multiple requests or updates at same time. It is just a validation error and I guess that the code 400 is more correct.

**Comment by matthewcummings** [comment]
I think 409 would be better but this is not a huge issue.
