### ISSUE TITLE
More typos, changes for the Sent Text Messages page.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#50]
https://www.textmagic.com/docs/api/send-sms/
- Change 
  "The main reason you would use the TextMagic API is to send texts. So, we’ve prepared detailed documentation about how to do that. The documentation covers the following aspects:" 
  to
  "The primary reason for using the TextMagic API is to send SMS text messages.  This page describes the following details about sending messages:"
- The following are minor but they sound better, in the Parameters table, make these changes:
  In the _text_ and _templateId_ rows, change the first sentences to "The message text."  and "The message template ID."  They are not grammatically complete sentences but I think that's fine in this case.
- In the contacts row, change this "Send message to this array of contacts." to "Send a message to this list of contacts."  The word 'list' sounds better here because the user needs to pass a comma delimited string, not an actual array.  I realize that 'list' also means contact list in Textmagic but I still think this wording is better.
- In the lists row, change this "Send message to the contacts in these lists." to "Send a message to the contacts in these contact lists."
- Also in the lists row, there's a typo.  This text "Note, th list IDs" should be "Note, the list IDs"
- In the phones row, change "Send message to this array of phone numbers in" to "Send a message to this list of phone numbers in"
- In the sendingTime row, change "Schedule sending a message at a specified time." to "Schedule a message to be sent at the specified time."
- In the Response section, change
  "If your request is unsuccessful, a standard error message will be returned. Otherwise, you will receive a special sending result (with a slightly enhanced link response):"
  to 
  "If your request is unsuccessful, you will receive an HTTP error code along with an error message. Otherwise, you will an HTTP success code (e.g. 200, 201, 204) and JSON response body with the following properties.
- In the Response table, I'd make a number of changes like with the Parameters table e.g.
  id row, "Main returned resource ID." -> "The main returned resource ID."
  href row, "Link to main returned resource ID" -> "A link to the main returned resource" (the link is to the resource NOT to the ID)
  type row, "Main returned" -> "The main returned"
  sessiondId row, "Sender sending session ID." -> "Sending session ID."  (It sounds bad to say 'sender sending' and it's clear without the word 'sender')
  bulkId row, "Bulk sender sending session ID." -> "The bulk sending session ID."
  messageId row, "Message ID (not session)." -> "The message ID (not session)."
  scheduleId row, "Schedule ID." -> "The schedule ID."
- In the How to send a single text message section, change
  "For example, to send an SMS to mobile with the text “I love TextMagic” to +44 (0) 7 860021130, you should use the command:"
  to
  "For example, to send an SMS message with the text “I love TextMagic” to the phone number +44 (0) 7 860021130, use this command:"
- Also, change
  "Since this was not a bulk session or scheduled message, bulkId and scheduleId are empty."
  to
  "Since this is not a bulk session or scheduled message, bulkId and scheduleId will be null."
- In the bulk section, change
  "with thefollowing parameters:"
  to 
  "with the following parameters:"
- Change
  "Since processing such a large session could take a long time (i.e. more than a few seconds), the messages are put into a queue. You can check the status and progress by sending a GET to:"
  to
  "Since processing such a large session could take a long time (i.e. more than a few seconds), the messages are stored in a queue temporarily. You can check the progress of the messages by sending a GET to:"
- Change 
  "Adequate balance in your account to send this SMS to the contact list."
  to 
  "A sufficient balance in your account to send this SMS message to the contact list."

*Change
"you can get messages session and"
to
"you can get the session for the messages and"
- Change
  "You can now use TextMagic API to send messages one by one and in bulk."
  to 
  "You can now use TextMagic API to send messages one at a time or in bulk."

**Comment by dmitry-textmagic** [comment]
Fixed.
