### ISSUE TITLE
Typos and changes for the Receive Text Messages page.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#51]
- "With TextMagic API v2, you can establish a full two-way communication to send messages and receive inbound text messages directly to your own application."
  ->
  "With the TextMagic API, you can establish a full two-way communication pipeline for sending and receiving  text messages within your application."
- A callback is a mechanism that calls a URL on your server. It also passes inbound messages, which are sent to your TextMagic account. You can also write a script that can save them into a database, show user notifications, turn on a parcel packing robot, and so forth.
  -> 
  "A callback is a mechanism that posts the JSON body of a received message to the URL on a server that you specify.  The server application which receives the callback can save the message data into a database, send user notifications, etc."  [parcel packing robot sounds odd, I understand what you're trying to say, but I'd just leave it out - the point is that the server can do ANYTHING with the callback data].
- "where id is a numeric inbound message ID. This command has no parameters."
  ->
  "where id is the unique numeric ID for the inbound message. This command has no parameters."
- In the response format table:
  id, "Inbound message ID." -> "The ID of the inbound message."
  sender, "Sender phone number." -> "The sender's phone number."
  receiver, "Receiver phone number (i.e. your dedicated or shared reply number)." -> "The receiver's phone number (i.e. your dedicated or shared reply number)."
  messageTime, "Time when message reached the TextMagic server." -> "The time when the message reached the TextMagic API endpoint."
  text, "Inbound message text." -> "The text from the received message."
- "where id is a numeric inbound message ID. This command has no parameters. If successful, this command will return the standard delete response (204 No Content). Otherwise, you’ll receive the standard error response."
  -> 
  "where id is the unique numeric ID for the inbound message.  This command takes no parameters. If successful, it will return the standard HTTP status code for a DELETE (204 No Content). Otherwise, you’ll receive an HTTP error code and an error message."

**Comment by dmitry-textmagic** [comment]
Fixed.
