### ISSUE TITLE
Typos/suggestions for the Invoices page

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#53]
https://www.textmagic.com/docs/api/invoices/#get-all-invoices
- Change
  "You can check your invoices and transactions using the TextMagic SMS API."
  to 
  "With the TextMagic API, you can check the invoices and transactions for your account.
- Change
  "To view all your invoices, use:"
  to 
  "To view all of your invoices, use:
- Change
  "Array of invoice"
  to 
  "Array of invoices" OR "Array of invoice objects" OR "List of invoices"
- Change
  "Invoice ID" to "The invoice ID"
- OK, the two "top up" items sound odd to me.  I'm American and this just isn't a phrase that we use although it is common in British English.  I don't know if you care about that though i.e. maybe most of your customers are in the EU, in which case this is perfectly fine.  However, if you want the doc to have more of a Transatlantic sound, I would make these changes:
  "Top up amount." to "Credit amount"
  and
  "Top up currency." to "Credit currency."
- Change
  "Now you’ve learned how to view your invoices via the TextMagic API. You can now check our Code libraries to view ready-made scripts in different languages, which can be applied for a faster implementation of TextMagic API."
  to
  "Now that you’ve learned how to view your invoices via the TextMagic AP, you can check our Code libraries to view ready-made scripts in different languages which you can use to quickly build powerful SMS based applications."
  [NOTE: I'm not sure what the faster implementation part is supposed to mean, I think you want to say that it's easy to build apps with the API].

**Comment by dmitry-textmagic** [comment]
Replaced all suggestions except "top up" one: you are right, "Top up" is more familiar to most of customers. Thanks.

NOTE: changes will be applied during next site rebuild process.
