### ISSUE TITLE
Update to the page/limit/pageCount descriptions.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#54]
This affects many of the doc pages, but it's basically the same set of updates for all of them.  The current wording is slightly awkward and confusing for the common request/response parameters.
- Change "Fetch specified results page. Default is 1." 
  to 
  "Fetch the specified results page. The default is 1."
- Change "How many results to return. Default is 10."
  to
  "The number of results per page.  The default is 10."
- Change "Current fetched page."
  to
  "The current fetched page."
- Change "Current limit of resources fetched per page."
  to
  "The number of results per page."
- Change "Page count."
  to
  "The total number of pages."

**Comment by dmitry-textmagic** [comment]
Changed throughout the site.

NOTE: changes will be applied during next site rebuild process.
