### ISSUE TITLE
Bad error message when the text body exceed 918 characters.

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#6]
This is a bug in the underlying REST API, not the Ruby wrapper, the response body looks like this:

```
{
  "code": 400,
  "message": "Validation Failed",
  "errors": {
    "common": [
      "Message text should not exceed 0 characters."
    ],
    "fields": {
      "text": [
        "Message text should not exceed 918 characters"
      ]
    }
  }
}
```

The common message is both redundant and incorrect.  My vote is to remove it completely and just keep the fields message.

**Comment by andreylarionov** [comment]
Will be fixed soon. Thanks.
