### ISSUE TITLE
Changes to the API Introduction page

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#7]
https://www.textmagic.com/docs/api/
The first paragraph reads like this:

> TextMagic SMS API is a platform for building your own messaging app using our messaging infrastructure. It allows you to send and receive SMS text messages, query information about inbound and outbound messages, manage contacts, create templates (i.e. message formats and static texts), and schedule recurrent & process bulk SMS messages.

I would change it to this:
The TextMagic SMS API is a platform for building your own messaging app using our infrastructure. It allows you to send and receive SMS text messages, query metadata for inbound and outbound messages, manage contacts, create message templates (i.e. use pre-defined formats and content), schedule recurring messages and process bulk SMS messages.

> Two Ways to Use TextMagic API

That line needs to be changed to 
Two Ways to Use the TextMagic API

> We have created a set of client libraries for the most popular programming languages (such as REST API Java and REST API PHP). These libraries will let you integrate our API into your code in minutes. Just choose your preferred language to get started:

I'd change it to this:
We have created a set of client libraries for the most popular programming languages (such as Java and PHP). These libraries will allow you to integrate our REST API into your code in minutes. Just choose your preferred language to get started:

**Comment by andreylarionov** [comment]
Will be fixed soon. Thanks.
