### ISSUE TITLE
Changes to the API Getting Started Page

### ISSUE THREAD

**Issue by matthewcummings** [textmagic/textmagic-rest-ruby#8]
> Getting Started with TextMagic REST API

Getting Started with the TextMagic REST API

> To start sending text messages using TextMagic REST API, do the following steps: 

To start sending text messages using the TextMagic REST API, follow these steps:

```
1. Generate API credentials
2. Connect to our API endpoint

This page will provide all the information you need to get started.

Obtaining Credentials
API Endpoint
How REST API works
Next Steps
```
1. Obtain API credentials [Anchor Tag]
2. Connect to our API endpoint [Anchor Tag]
3. Learn how REST APIs work [Anchor Tag]
4. Next Steps [Anchor Tag]

> The only difference is that API key allows you to access only the API: you cannot login to TextMagic Online using the API key

The difference is that an API key only provides access to the API: you cannot login to TextMagic Online using the API key.

> 1. Log in to TextMagic (or start a free trial if you haven’t registered yet).
> 2. Go to API.
1. Log in to TextMagic[Link](or start a free trial if you haven’t registered yet).
2. Go to the API settings page[Link].

> V1 keys are not compatible with the current REST API. You need to generate a new API key to use TextMagic REST API.

V1 keys are not compatible with the V2 version of the TextMagic REST API. You will need to generate a new API key to use the V2 endpoint.

> How REST API works

REST uses the Internet’s HTTP protocol to call web services using JSON documents. It is an improvement over the older ways of doing that, which are SOAP XML messages or directly linking to an API. This is because REST is natural and easy to use as it works just like regular web pages. It uses a small set of commands: create, read, and update. You can call a function (web service) by populating a JSON message and then indicate in the URL what function you want to call, like, for example, http://api.foo.com/doSomething. Then you do a simple HTTP GET, PUT, DELETE, or POST.

How REST APIs work

REST APIs use the HTTP protocol to send and receive messages. REST messages are usually encoded as JSON documents and are an improvement over older methods such as the XML based SOAP protocol. REST APIs use the same set of methods that web browsers use: POST, GET, PUT and DELETE.  These correspond to the CRUD operations:  create, read, update and delete.  Oftentimes, REST URIs provide direct CRUD access to entities or collections of entities: for example: http://api.foo.com/people.  For example, to delete a person endpoint, you might simply call DELETE http://api.foo.com/people/{id}.  REST makes these types of operations simple.

> Example
> Let’s take the entity most often used in messaging: contacts. With REST you can create, read, update, or delete contacts.

TextMagic Example
Let's look at an example in the TextMagic REST API.  Let's say you want to perform operations on your contacts list, it's only a matter of calling the following endpoints:
GET /api/v2/contacts (get all of your contacts)
GET /api/v2/contacts/{id} (get a specific contact)
POST /api/v2/contacts (create a new contact, the contact info is sent in the body of the request)
PUT /api/v2/contacts/{id} (update an existing contact, the update info is sent in the body of the request)
DELETE /api/v2/contacts/{id}
It’s that simple! That’s all you need to do to manage contacts in your TextMagic account!

> You’re now on your way to TextMagic Sandbox, which you can try (by request) before writing the code.

NOT SURE WHAT "before writing the code" IS SUPPOSED TO MEAN.  I'd go with something like
You’re now on your way to TextMagic Sandbox, which you can try (by request) without writing any code.

**Comment by andreylarionov** [comment]
Will be fixed soon. Thanks.

**Comment by sohaibameen** [comment]
Hi, 

I am trying to create a free trial account in Pakistan to use TextMagic API but It says "Text Magic is not available in your location". Is there any single way to work this out so I can use it?

Answer will be much appreciated. Thanks
